/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package schedulerComponents;

import java.util.List;
import com.mycompany.process.Process;
import com.mycompany.process.Queue;

/**
 *
 * @author LENOVO
 */
public class navigationPanel extends javax.swing.JPanel {
	private final processConfig proConfig;
	private mlfqConfig queueConfig;


    /**
     * Creates new form navigationPanel
     */
    public navigationPanel() {
        initComponents();
	proConfig = new processConfig();
	queueConfig = new mlfqConfig();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jToggleButton1 = new javax.swing.JToggleButton();
                clockSpeed = new javax.swing.JComboBox<>();
                startSimulation = new javax.swing.JToggleButton();
                stopSimulation = new javax.swing.JToggleButton();
                jSeparator2 = new javax.swing.JSeparator();
                jSeparator3 = new javax.swing.JSeparator();

                jToggleButton1.setText("jToggleButton1");

                clockSpeed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10ms", "50ms", "100ms", "1s" }));

                startSimulation.setText("Start Simulation");
                startSimulation.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                startSimulationActionPerformed(evt);
                        }
                });

                stopSimulation.setText("STOP");
                stopSimulation.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                stopSimulationActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(clockSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stopSimulation)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(startSimulation)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(startSimulation)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(stopSimulation, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(clockSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                clockSpeed.getAccessibleContext().setAccessibleName("");
                startSimulation.getAccessibleContext().setAccessibleName("startSimulationButton");
                stopSimulation.getAccessibleContext().setAccessibleName("stop button");
        }// </editor-fold>//GEN-END:initComponents

    private void startSimulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startSimulationActionPerformed

    }//GEN-LAST:event_startSimulationActionPerformed

    private void stopSimulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopSimulationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stopSimulationActionPerformed

    public int getClockSpeed(){
	    String selectedSpeed = (String) clockSpeed.getSelectedItem();
	    return extractInteger(selectedSpeed);
    }


        // Variables declaration - do not modify//GEN-BEGIN:variables
        public javax.swing.JComboBox<String> clockSpeed;
        private javax.swing.JSeparator jSeparator2;
        private javax.swing.JSeparator jSeparator3;
        private javax.swing.JToggleButton jToggleButton1;
        public javax.swing.JToggleButton startSimulation;
        private javax.swing.JToggleButton stopSimulation;
        // End of variables declaration//GEN-END:variables

	private int extractInteger(String str) {
		String numericString = str.replaceAll("[^\\d]", "");
		return Integer.parseInt(numericString);
	}
}
