/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package schedulerComponents;
import javax.swing.JOptionPane;

import com.mycompany.process.ProcessGenerator;
import com.mycompany.process.Process;
import java.util.List;
import javax.swing.JPanel;
import java.awt.*;
import java.util.ArrayList;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JViewport;

/**
 *
 * @author LENOVO
 */
public class processConfig extends javax.swing.JPanel {

	public List<processPanel>processList = new ArrayList<>();
	public List<Process> processes = new ArrayList<>();
    /**
     * Creates new form processConfig1
     */
    public processConfig() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
//     @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                menuBar1 = new java.awt.MenuBar();
                menu1 = new java.awt.Menu();
                menu2 = new java.awt.Menu();
                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                nProcessInput = new javax.swing.JTextField();
                generateProcess = new javax.swing.JButton();
                clearProcess = new javax.swing.JButton();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                randomizeProcess = new javax.swing.JToggleButton();
                jSeparator1 = new javax.swing.JSeparator();
                jSeparator2 = new javax.swing.JSeparator();
                jSeparator3 = new javax.swing.JSeparator();
                processObjectPane = new javax.swing.JScrollPane();
                processObjectsPanel = new javax.swing.JPanel();

                menu1.setLabel("File");
                menuBar1.add(menu1);

                menu2.setLabel("Edit");
                menuBar1.add(menu2);

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
                );

                jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
                jLabel1.setText("Processes");

                jLabel2.setText("No. of Processes");

                nProcessInput.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                nProcessInputActionPerformed(evt);
                        }
                });

                generateProcess.setText("Generate");
                generateProcess.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                generateProcessActionPerformed(evt);
                        }
                });

                clearProcess.setText("Clear");
                clearProcess.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                clearProcessActionPerformed(evt);
                        }
                });

                jLabel3.setText("Process ID");

                jLabel4.setText("Arrival Time");

                jLabel5.setText("Burst Time");

                jLabel6.setText("Priority");

                randomizeProcess.setText("Randomize");
                randomizeProcess.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                randomizeProcessActionPerformed(evt);
                        }
                });

                processObjectPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
                processObjectPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

                javax.swing.GroupLayout processObjectsPanelLayout = new javax.swing.GroupLayout(processObjectsPanel);
                processObjectsPanel.setLayout(processObjectsPanelLayout);
                processObjectsPanelLayout.setHorizontalGroup(
                        processObjectsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 496, Short.MAX_VALUE)
                );
                processObjectsPanelLayout.setVerticalGroup(
                        processObjectsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 329, Short.MAX_VALUE)
                );

                processObjectPane.setViewportView(processObjectsPanel);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(randomizeProcess)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(processObjectPane)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel2)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(nProcessInput)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(generateProcess)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(clearProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel1)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(14, 14, 14)
                                                                                .addComponent(jLabel3)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jLabel4)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(jLabel5)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jLabel6)))
                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                .addContainerGap())))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(nProcessInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(generateProcess)
                                                        .addComponent(clearProcess)
                                                        .addComponent(jLabel2))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel3)
                                                                .addComponent(jLabel4)
                                                                .addComponent(jLabel5))
                                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel6)))
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(processObjectPane)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(randomizeProcess)
                                .addContainerGap())
                );

                nProcessInput.getAccessibleContext().setAccessibleName("nProcesses");
                generateProcess.getAccessibleContext().setAccessibleName("generateProcess");
                clearProcess.getAccessibleContext().setAccessibleName("clearNProcess");
        }// </editor-fold>//GEN-END:initComponents

    private void clearProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearProcessActionPerformed
	nProcessInput.setText("");
	processList.clear();
	processes.clear();
	processObjectsPanel.removeAll();
	processObjectsPanel.revalidate();
	processObjectsPanel.repaint();
	
    }//GEN-LAST:event_clearProcessActionPerformed

    private void randomizeProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomizeProcessActionPerformed
	    generateProcessActionPerformed(evt);
    }//GEN-LAST:event_randomizeProcessActionPerformed

        private void nProcessInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nProcessInputActionPerformed
		nProcessInputActionPerformed(evt);

        }//GEN-LAST:event_nProcessInputActionPerformed

        private void generateProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateProcessActionPerformed
		processList.clear();
		processes.clear();
		processObjectsPanel.removeAll();
//		clearProcessActionPerformed(evt);
		String inputText = nProcessInput.getText();
		int numberOfProcesses;
		
//		JViewport viewport = processObjectPane.getViewport();
		


		try{
			numberOfProcesses = Integer.parseInt(inputText);

		} catch (NumberFormatException e){
			JOptionPane.showMessageDialog(this, "Invalid number of processes. Please input an integer.", "Error", JOptionPane.ERROR_MESSAGE);
			return;
		}
                ProcessGenerator processGenerator = new ProcessGenerator();
		processes = processGenerator.generateProcesses(numberOfProcesses);
		StringBuilder processInfo = new StringBuilder();
		for (Process process : processes) {
		    processInfo.append(process.toString()).append("\n");
		    processPanel newProcess = new processPanel();
		    newProcess.processID.setText(Integer.toString(process.id));
		    newProcess.arrivalTime.setText(Integer.toString(process.arrivalTime));
		    newProcess.burstTime.setText(Integer.toString(process.burstTime));
		    newProcess.priority.setText(Integer.toString(process.priority));
		    processList.add(newProcess);
		}
		
		System.out.println(processInfo);

		processObjectsPanel.setLayout(new BoxLayout(processObjectsPanel, BoxLayout.Y_AXIS));
		for(processPanel panel: processList){
			processObjectsPanel.add(panel);
			processObjectsPanel.revalidate();
		}
		processObjectPane.revalidate();
        }//GEN-LAST:event_generateProcessActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton clearProcess;
        private javax.swing.JButton generateProcess;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JSeparator jSeparator2;
        private javax.swing.JSeparator jSeparator3;
        private java.awt.Menu menu1;
        private java.awt.Menu menu2;
        private java.awt.MenuBar menuBar1;
        private javax.swing.JTextField nProcessInput;
        private javax.swing.JScrollPane processObjectPane;
        private javax.swing.JPanel processObjectsPanel;
        private javax.swing.JToggleButton randomizeProcess;
        // End of variables declaration//GEN-END:variables
}
