/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package schedulerComponents;

/**
 *
 * @author LENOVO
 */
public class processPanel extends javax.swing.JPanel {

    /**
     * Creates new form process
     */
    public processPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                processGenerator1 = new com.mycompany.process.ProcessGenerator();
                jSeparator1 = new javax.swing.JSeparator();
                jSeparator2 = new javax.swing.JSeparator();
                processID1 = new javax.swing.JLabel();
                arrivalTime = new javax.swing.JLabel();
                processID = new javax.swing.JLabel();
                burstTime = new javax.swing.JLabel();
                priority = new javax.swing.JLabel();

                processID1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                processID1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                processID1.setText("Process ID");

                arrivalTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                arrivalTime.setText("Arrival Time");
                arrivalTime.setAlignmentY(0.0F);
                arrivalTime.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                arrivalTime.setDoubleBuffered(true);

                processID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                processID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                processID.setText("Process ID");

                burstTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                burstTime.setText("Burst Time");
                burstTime.setAlignmentY(0.0F);
                burstTime.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                burstTime.setDoubleBuffered(true);

                priority.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                priority.setText("Priority");
                priority.setAlignmentY(0.0F);
                priority.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                priority.setDoubleBuffered(true);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(processID)
                                .addGap(60, 60, 60)
                                .addComponent(arrivalTime, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(burstTime, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(priority, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(processID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(arrivalTime, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(burstTime, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(priority, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                );

                arrivalTime.getAccessibleContext().setAccessibleName("arrivalTime");
                arrivalTime.getAccessibleContext().setAccessibleDescription("");
                processID.getAccessibleContext().setAccessibleName("processID");
                burstTime.getAccessibleContext().setAccessibleName("burstTime");
                priority.getAccessibleContext().setAccessibleName("priority");
        }// </editor-fold>//GEN-END:initComponents


        // Variables declaration - do not modify//GEN-BEGIN:variables
        public javax.swing.JLabel arrivalTime;
        public javax.swing.JLabel burstTime;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JSeparator jSeparator2;
        public javax.swing.JLabel priority;
        private com.mycompany.process.ProcessGenerator processGenerator1;
        public javax.swing.JLabel processID;
        public javax.swing.JLabel processID1;
        // End of variables declaration//GEN-END:variables
}
