/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package schedulerComponents;

/**
 *
 * @author LENOVO
 */
public class processBlock extends javax.swing.JPanel {

    /**
     * Creates new form processBlock
     */
    public processBlock() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                processID = new javax.swing.JLabel();

                processID.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
                processID.setText("ID");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(processID)
                                .addContainerGap(55, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(47, Short.MAX_VALUE)
                                .addComponent(processID)
                                .addContainerGap())
                );

                processID.getAccessibleContext().setAccessibleName("processID");
        }// </editor-fold>//GEN-END:initComponents

	public void setProcessID(int ID){
		processID.setText(String.valueOf(ID));
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        public javax.swing.JLabel processID;
        // End of variables declaration//GEN-END:variables
}
