/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package schedulerComponents;

/**
 *
 * @author LENOVO
 */
public class queuePanel extends javax.swing.JPanel {

    /**
     * Creates new form queue1
     */
    public queuePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jFrame1 = new javax.swing.JFrame();
                jTextField1 = new javax.swing.JTextField();
                schedAlgo = new javax.swing.JComboBox<>();
                processID = new javax.swing.JLabel();
                schedAlgoOption = new javax.swing.JComboBox<>();
                quantumInput = new javax.swing.JTextField();
                queueID = new javax.swing.JLabel();

                jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jTextField1.setText("Queue");
                jTextField1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextField1ActionPerformed(evt);
                        }
                });

                schedAlgo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

                javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
                jFrame1.getContentPane().setLayout(jFrame1Layout);
                jFrame1Layout.setHorizontalGroup(
                        jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jFrame1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(schedAlgo, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jFrame1Layout.setVerticalGroup(
                        jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(schedAlgo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17))
                );

                processID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                processID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                processID.setText("Process ID");

                schedAlgoOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "First Come First Serve", "Shortest Job First", "Shortest Remaining Time First", "Non-preemptive CPU", "Preemptive", "Round Robin" }));
                schedAlgoOption.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                schedAlgoOptionActionPerformed(evt);
                        }
                });

                quantumInput.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                quantumInputActionPerformed(evt);
                        }
                });

                queueID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                queueID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                queueID.setText("Queue ID");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(queueID)
                                .addGap(18, 18, 18)
                                .addComponent(schedAlgoOption, 0, 360, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(quantumInput, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(schedAlgoOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(quantumInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(queueID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );
        }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

        private void quantumInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantumInputActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_quantumInputActionPerformed

        private void schedAlgoOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schedAlgoOptionActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_schedAlgoOptionActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JFrame jFrame1;
        private javax.swing.JTextField jTextField1;
        public javax.swing.JLabel processID;
        public javax.swing.JTextField quantumInput;
        public javax.swing.JLabel queueID;
        private javax.swing.JComboBox<String> schedAlgo;
        public javax.swing.JComboBox<String> schedAlgoOption;
        // End of variables declaration//GEN-END:variables
}
